### ISSUE TITLE
Failed clinical sample

### ISSUE THREAD

**Issue by skanwal** [umccr/RNAsum#109]
We had recently a failed WTS sample - details are:

- https://data.umccr.org/subjects/SBJ03874
- wfr.a46a39b2875549f685317e1f82c44c0f
- trn.8566f439dd7b44d980dc4ba92cfd74dd

```
gds-view --gds-path gds://production/temp/analysis_data/SBJ03874/rnasum/20230716943afa24/logs/main/try-1/task-stdouterr-0.log --to-stdout


processing file: RNAseq_report.Rmd
  |                                                                      |   0%
   inline R code fragments

  |.                                                                     |   1%
label: script_description (with options)
List of 1
 $ eval: logi FALSE

.
.
.
.                                                 |  28%
label: fusions_annot (with options)
List of 4
 $ comment: logi NA
 $ message: logi TRUE
 $ warning: logi FALSE
 $ eval   : logi TRUE

[1] "Start: 2023-07-16 13:02:32"
[1] "Stop: 2023-07-16 13:02:32"
Time difference of 0.03456378 secs
  |....................                                                  |  29%
  ordinary text without R code


label: fusions_and_manta_data_prep (with options)
List of 4
 $ comment: logi NA
 $ message: logi FALSE
 $ warning: logi FALSE
 $ eval   : logi TRUE

[1] "Start: 2023-07-16 13:02:32"
Quitting from lines 3935-3989 (RNAseq_report.Rmd)
Error in order(..., decreasing = decreasing) : argument 3 is not a vector
Calls: <Anonymous> ... order -> standardGeneric -> eval -> eval -> eval -> order
In addition: There were 30 warnings (use warnings() to see them)

Execution halted
```

This will be a good test case for recent refactoring work to see if we can capture this issue.

**Comment by ohofmann** [comment]
In the absence of a QC-based go/no-go decision from the portal and workflow managers do you want to add in a QC check to the WTS workflow? E.g., if file sizes smaller X skip to the end of the pipeline.

**Comment by skanwal** [comment]
Although shallow, but this sample has ~15M input reads. Looking at the error, it has failed at fusion prep stage and producing an R error. I'd like to understand which input is choking RMD and if this is handled better/differently with refactored code.

**Comment by pdiakumis** [comment]
We haven't nailed this one down yet have we?
I can debug SBJ03874 from my side if so.

**Comment by skanwal** [comment]
I haven't added this case to my testing cohort. Leaving it with you :)

**Comment by pdiakumis** [comment]
Getting same error with https://umccr.slack.com/archives/C8CG6K76W/p1693072750986549.

**Comment by victorskl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Portal Release - Ocicat: Update BioInfo platform with RNAsum 0.4.9](https://trello.com/c/4x3cFDCE/1544-portal-release-ocicat-update-bioinfo-platform-with-rnasum-048)
