### ISSUE TITLE
Handle new ensembl gene annotations

### ISSUE THREAD

**Issue by skanwal** [umccr/RNAsum#110]
Currently, we expect ensembl gene name to have a format like `ENSG00000223972`. This only works with older ensembl database versions.  Using ensembl v105, the gene names are like `ENSG00000223972.5` - i.e. have a version number after decimal. 
This errors out when joining sample count matrix with reference data matrix that has ensembl gene names without decimal.

 We should strip out version from from ensembl gene names when reading in counts information for a sample.

**Comment by skanwal** [comment]
Additionally, we have `PAR_Y` contigs in gencode v39. From gencode release 25, the PAR genes and transcripts have "_PAR_Y" appended to their ids. We have decided to keep only the ones without PAR_Y:

```
The gene annotation is the same in both ensembl and gencode files. The only exception is that the genes which are common to the human chromosome X and Y PAR regions can be found twice in the GENCODE GTF, while they are shown only for chromosome X in the Ensembl file.
```

**Comment by skanwal** [comment]
In order to work with Dragen4.2.4, we need to port the changes for this issue to master branch.

**Comment by victorskl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Portal Release - Ocicat: Update BioInfo platform with RNAsum 0.4.8](https://trello.com/c/4x3cFDCE/1544-portal-release-ocicat-update-bioinfo-platform-with-rnasum-048)
