### ISSUE TITLE
Handle NAs in fusion_annot object

### ISSUE THREAD

**Issue by pdiakumis** [umccr/RNAsum#35]
Having rows with `<NA>` causes the `circos_prep` section to crash with error:

```
Error in RCircos.Validate.Genomic.Data(genomic.data, "plot", genomic.columns) :
  Some chromosomes in plot data is not in ideogram.
```

**Comment by JMarzec** [comment]
Thanks Peter for providing the solution for that issue, it works well.

**Comment by xiongyf520** [comment]
why my data do not have NAs ,and chr name is matched to UCSC.HG38.Human.CytoBandIdeogram$Chromosome, but still have this bug.
