### ISSUE TITLE
Dockerfile? Tests?

### ISSUE THREAD

**Issue by brainstorm** [umccr/RNAsum#38]
@reisingerf @skanwal @JMarzec IIRC you build docker containers with this repo, right? Where is the `Dockerfile` in this project?

Is there any (small) testsuite we could run to validate this software installs successfully? Functional tests would be good, but I understand it could be tricky to put together for this project.

**Comment by skanwal** [comment]
@brainstorm the docker file is located [here])https://github.com/umccr/RNAsum/blob/master/envm/Dockerfile)

And we have a small test data in this repo to help with software/updates testing https://github.com/umccr/RNAsum/tree/master/data/test_data

I can add some documentation around using this test data with the docker container - if that's what you're asking?

**Comment by brainstorm** [comment]
I'm looking for something like this on the README or docs:

https://github.com/umccr/umccrise/commit/09ebeed99f4047fe4c345a9aefd22f7f82c9a63a

**Comment by skanwal** [comment]
Done! 
Update instructions [here](https://github.com/umccr/RNAsum/blob/49ebda18251fa2edb4c79e36e0efe13348f77492/README.md#docker).

Feedback welcome.

**Comment by JMarzec** [comment]
The corresponding documentation was added and that issue is resolved
