### ISSUE TITLE
Handle umccrise v1.2.0 outputs

### ISSUE THREAD

**Issue by pdiakumis** [umccr/RNAsum#44]
* `manta.tsv`: contains an extra column at the end (`ALT`). In umccrise we handle the reading/processing of this via gpgr in <https://github.com/umccr/gpgr/blob/master/R/sv.R#L195>. We have a conda package for it at <https://anaconda.org/pdiakumis/r-gpgr> but it's only supported for R v4.0 and above.
* `purple.cnv.gene.tsv`: you're lucky PURPLE v2.51 only changed the `minMinorAllelePloidy` column to `minMinorAlleleCopyNumber`, which I don't think you parse.

**Comment by JMarzec** [comment]
Thanks @pdiakumis for info. We may need to adapt your code to handle the new manta output format. Purple should be fine, we only parse the `Ploidy_PURPLE` (`Ploidy`) column.

**Comment by pdiakumis** [comment]
I'm guessing you'd only need to add an extra `c` at https://github.com/umccr/RNAsum/blob/master/rmd_files/RNAseq_report.Rmd#L1555

Depending on which columns you'd want to display in the report, you can also take advantage of `readr`'s `cols_only()` function, e.g. I have a function like this in gpgr:

```
 cnv <- readr::read_tsv(x,
                         col_types = readr::cols_only(
                           "chromosome" = "c", "start" = "i", "end" = "i",
                           "copyNumber" = "d", "minorAlleleCopyNumber" = "d"))
```

**Comment by JMarzec** [comment]
Thanks @pdiakumis for great pointers. All works well!
