### ISSUE TITLE
Fusion output format - backward compatability

### ISSUE THREAD

**Issue by skanwal** [umccr/RNAsum#47]
In a recent discussion with Sigve, it was mentioned that the report doesn't work against Dragen-v3.7.

Looking back at the commit history - think this was introduced in https://github.com/umccr/RNAsum/commit/23b18ec23d01107fa11554d09403a19f03ff9ca3 as I was initially testing RNasum against v3.7 in [PR#43 ](https://github.com/umccr/RNAsum/commit/23b18ec23d01107fa11554d09403a19f03ff9ca3).  
Now that we have moved to v3.9, the PR was updated to work against respective 3.9 outputs. 

We can update RNAsum code to be backward compatible with Dragen outputs as I don't expect it to be too much work.
Any opinions - @ohofmann @JMarzec ?

**Comment by ohofmann** [comment]
In favor :)

**Comment by JMarzec** [comment]
That's 100% correct whaat @skanwal wrote. And yes, we can update RNAsum so that it's compatible with both versions if required. It shouldn't be much work

**Comment by skanwal** [comment]
@JMarzec - your thoughts are welcome as we have another vote ;)

**Comment by skanwal** [comment]
Closing as fixed with https://github.com/umccr/RNAsum/pull/48.
