### ISSUE TITLE
Error report regarding to "fusions_filtering" at when only Dragen RNA fusion callings are available

### ISSUE THREAD

**Issue by senzhaocode** [umccr/RNAsum#49]
Hi RNAsum developer, 

I think "split_reads" column is absent in the data.frame object "fusion_annot" at line 3801 
```
} else if ( runDragenFusionChunk ) {
  fusion_annot <- cbind(fusion_annot1, fusion_annot2, fusions.annot[, c("Score", "LeftBreakpoint", "RightBreakpoint", "reported_fusion", "fusions_cancer", "reported_fusion_geneA", "reported_fusion_geneB")])
```

It gives rise to an error for "fusion_annot" filtering at line 3881 (Not certainty for Score > 1  or Score > 0 ???)
```
fusion_annot <- fusion_annot %>% dplyr::filter(split_reads > 1 | Score > 1 | geneA_dna_support != "-" | geneB_dna_support != "-" | reported_fusion != "-" | fusions_cancer != "-")
```

<img width="526" alt="Screenshot 2022-01-19 at 22 40 19" src="https://user-images.githubusercontent.com/26706345/150219762-a7bb36d3-1113-4ec1-8175-26119627b03e.png">

**Comment by skanwal** [comment]
Hi @senzhaocode , 

Sorry about the issue. Can you confirm this is for fusion output from Dragen-v3.7.5? 
Think, this version doesn't report split reads explicitly and that could be problematic if Arriba fusion output is also absent.

I suspect, we have been testing with both Arriba and Dragen fusion outputs and hence didn't hit this bug.

**Comment by senzhaocode** [comment]
Yes, when Arriba and Dragen fusion callings are available, no problem for it. But we do not have Arriba fusion output for our own data right now, so I got stuck due to this bug. BTW, this is related to fusion out from Dragen-v3.9.3 (I have not tested it on Dragen-v3.7.5). Great that you could fix it

Thanks a lot!

**Comment by JMarzec** [comment]
That makes sense. Thanks for updates. We've updated the code to fix that bug and are testing it now. Will  notify you once all tests are completed

**Comment by JMarzec** [comment]
Hi @senzhaocode , the code has been updated and should be running smoothy using fusions output from both Dragen-v3.7.5 as well as  Dragen-v3.9.3. I hope it'll for you now.  Shout if you run into any problems.
