### ISSUE TITLE
Current docker build fails with conda dep/conflicts error

### ISSUE THREAD

**Issue by alexiswl** [umccr/RNAsum#53]
Error file attached

[docker.stderr.txt](https://github.com/umccr/RNAsum/files/8249061/docker.stderr.txt)

Can we reconsider [this PR](https://github.com/umccr/RNAsum/pull/45) to help resolve this?

**Comment by victorskl** [comment]
Does it block PR #52? Agree that we should work out PR #45 for base image upgrade -- it slight pass my radar somehow, sorry (i.e. re: me being in Reviewer in #45).
