### ISSUE TITLE
argument is of length zero

### ISSUE THREAD

**Issue by skanwal** [umccr/RNAsum#70]
In case `\\.mapping_metrics.csv$` is missing or not provided, RNAsum code errors out with:

```
Error in if ((file.exists(dragen_mapping_metrics) & length(dragen_mapping_metrics) ==  : 
  argument is of length zero
```

at https://github.com/umccr/RNAsum/blob/master/rmd_files/RNAseq_report.Rmd#L2159.

A possible solution is to instead use `if ( !rlang::is_empty(dragen_mapping_metrics))` as a condition.

@pdiakumis - let me know what you think of this?

**Comment by pdiakumis** [comment]
I'd keep it simple here, don't need to use `rlang` in this case. If you put the `length(...) == 1` condition first, you don't even need the other condition.
i.e. `if (length(dragen_mapping_metrics) == 1) ...`

Try this code out and see what's happening:

```
x <- list.files(pattern="foobar")
x
length(x) # 0
file.exists(x) # logical(0)

file.create("boo.txt")
y <- list.files(pattern = "boo")
y
length(y) # 1
file.exists(y) # TRUE
```

So we can get away with just using the `length`. If you have more than 1 match I guess it shouldn't make the decision for you and should instead just ignore them all.
