### ISSUE TITLE
Test data quitting from lines 1856-2194 - attempt to set an attribute on NULL

### ISSUE THREAD

**Issue by MonicaSolbakken** [umccr/RNAsum#75]
Dear RNAsum developers!

I am trying to use RNAsum on some cancer RNA data, but have met some obstacles. Currently I am trying to use the enclosed test data, but RNAsum is failing. I am struggling to pinpoint the issue as it is the last line of a code chunk that is failing. 

I have done the following (sorry about the pictures, but export from our HPC is heavily restricted due to sensitive data):

Dowloaded docker image for conversion to singularity using Singularity v. 3.8.7 on RNAsum 0.4.1.
The image was imported into our sensitive data HPC.

When running the container on the test data I run into the following error:
<img width="766" alt="Screenshot 2022-11-23 at 08 57 34" src="https://user-images.githubusercontent.com/11572773/203505321-22750166-64d1-4574-b5ea-6ff17edb30dd.png">

I am running the following script:
<img width="1224" alt="Screenshot 2022-11-23 at 08 59 37" src="https://user-images.githubusercontent.com/11572773/203505487-d667de4e-3a30-4a4d-9b32-166b8374b515.png">

I noticed that there might be some issues with the reference data carriage returns noted in #67 - I reformatted them using mac2unix + dos2unix, but this did not help. 

PS: initially the container complained about not being able to establish connection with the bus socket - therefore the additional bind to /run/dbus

PPS: the files RNAseq_report.R, RNAseq_report.RMd, and RNAseq_report.css all have to be in the folder from where singularity container is called in my SLURM script. This might be a trait of our HPC, but I mention it anyways in case it is something that can be changed. 

I might be missing something very trivial as I am new to using singularity containers, but trying here just in case.

**Comment by skanwal** [comment]
Hi @MonicaSolbakken ,

Sorry about the issue. Think I have found the bug that's is causing it and have proposed a fix in https://github.com/umccr/RNAsum/pull/76.

I'll let you know once I have pushed a new docker image against this update.

**Comment by MonicaSolbakken** [comment]
Thank you for your help! I edited a few additional sunburst commands in there with a misplaced ). Ran beautifully after that!
