### ISSUE TITLE
Potential issue for samples with few fusions and/or low expression / few pcgr entries

### ISSUE THREAD

**Issue by MonicaSolbakken** [umccr/RNAsum#78]
Dear RNAsum developers, 

I am currently working on ~100 samples from a clinical trial on the behalf of one of our users. These samples are exome sequenced (with pcgr report), total RNA sequenced with kallisto expression and arriba fusion calls. 

Of these samples there are 4 that fail when running RNAsum with the umccrise option (note that they do run through with only bcbio option) - see output from slurm:

<img width="905" alt="Screenshot 2022-12-03 at 12 39 04" src="https://user-images.githubusercontent.com/11572773/205439197-fcbe561c-cba8-4edb-908e-ff9942450859.png">

I am trying to pinpoint what the issue is. For reference the samples have the following number of fusions, variants and tiers:

Sample A 17 fusions, 1543 pcgr entries: 1027 noncoding, 37 TIER3 and 478 TIER4. 
Sample B 19 fusions, 195 pcgr entries: 160 noncoding, 4 TIER3, 30 TIER4. 
Sample C 16 fusions, 532 pcgr entries: 401 noncoding, 9 TIER3, 121 TIER4. 
Sample D 8 fusions, 43 pcgr entries: 39 noncoding, 1 TIER3, 2 TIER4. 

I have samples similar to sample B that have gone through without issues. Also, overall there is a large spread in terms of expression overall for each sample. Among the four failing, two of them have suboptimal mapping to the reference genome due to high levels of rRNA. 

I'm on version 0.4.1 as this has a docker image available, but I have included the modifications done on the .Rmd file from resolved issue #75 

Any thoughts on why these four samples may be failing?

Thanks for a great tool! Our users greatly appreciate the report format for their large amount of data.

All the best, 
Monica

**Comment by skanwal** [comment]
Hi @MonicaSolbakken 

Glad to know you have found RNAsum useful for your work :)

From the provided information, I can't debug what the issue can be. Specifically when 96% of these 100 samples have run successfully. Are you able to share minimal data and the commandline that reproduces the issue?

Best,
Sehrish

**Comment by skanwal** [comment]
Closing the issue. Feel free to open a new one if you need to discuss anything.
