### ISSUE TITLE
Update Ensembl

### ISSUE THREAD

**Issue by pdiakumis** [umccr/RNAsum#86]
Currently using v86 (from 2017). We should compare to v105 (from Dec 2021) which is the one used by PCGR v1.4.1.

**Comment by pdiakumis** [comment]
Currently team is finalising v105 testing.

**Comment by skanwal** [comment]
Closed with https://github.com/umccr/RNAsum/commit/d071fafc7ccc58d93a85e68ecdb952603a865846
