### ISSUE TITLE
Missing Fusion Handling

### ISSUE THREAD

**Issue by pdiakumis** [umccr/RNAsum#90]
Need to better handle missing/empty Arriba/Dragen fusion files.

Slack threads [A](https://umccr.slack.com/archives/C8CG6K76W/p1681870719156149), [B](https://umccr.slack.com/archives/C8CG6K76W/p1680952396590289)

I've worked on a fix in the rpackage branch but we might need to implement it differently in master for now.

**Comment by victorskl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Portal Release - Snowshoe: RNAsum Handle missing fusion calls](https://trello.com/c/OWGezQKg/1464-portal-release-snowshoe-rnasum-handle-missing-fusion-calls)
