### ISSUE TITLE
Update Fusion Filtration

### ISSUE THREAD

**Issue by pdiakumis** [umccr/RNAsum#91]
Need to get feedback from curation team about fusion filtration, but also allow more flexibility - master chunk at: https://github.com/umccr/RNAsum/blob/e1dc8ebe1dea0f7ea310eb5337340edcfb0110c6/rmd_files/RNAseq_report.Rmd#L3954

**Comment by skanwal** [comment]
Curation team suggests we keep it as is - "more is better"!
